### ISSUE TITLE
[PE-D][Tester A] Wrong image for the Find feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-T16-2/tp#172]
The image in the User Guide for under the `Locating persons by attribute: find` section, the image shown for the example of a successful output is not correct as shown below. This may cause confusion to the users on whether they are actually the right application.

![image.png](https://raw.githubusercontent.com/brendanneojw/ped/main/files/6f12e2f5-feda-41c9-a338-6fe803a4b450.png)

![image.png](https://raw.githubusercontent.com/brendanneojw/ped/main/files/34c59582-9b76-412e-85b1-750178103d64.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: brendanneojw/ped#2

**Comment by leezhanpeng** [comment]
Thanks, have missed this out.
