### ISSUE TITLE
[PE-D][Tester A] Format for Find feature is confusing

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-T16-2/tp#174]
According to the User Guide in the `Locating persons by attribute: find` section, the format for the `find` command given is very confusing. It looks like I can even do `find n/` without any value to the field given. Perhaps it will be clearer if you can put `find [n/NAME]` etc

![image.png](https://raw.githubusercontent.com/brendanneojw/ped/main/files/fa7595f4-3bbf-433a-8a32-fc48b16e4f33.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: brendanneojw/ped#3

**Comment by leezhanpeng** [comment]
Thanks for the suggestion. Will follow through with this new format: `(n | p | e | r | a)/KEYWORD [MORE KEYWORDS]...`
