### ISSUE TITLE
[PE-D][Tester D] Additional input for commands will still run the command [CLEAR and LIST comands]

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-T16-2/tp#175]
![Screenshot 2023-11-03 at 4.18.12 PM.png](https://raw.githubusercontent.com/ryanongwx/ped/main/files/c205f771-ab28-490c-8d14-cb7634bbc271.png)

Attackers may include their code within the clear command and your program will still run it and execute the command. If there is any malicious code added, it may break your application.

Prevent any extra inputs from being executed as it is an invalid command

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: ryanongwx/ped#2

**Comment by leezhanpeng** [comment]
As indicated in `features` of our UG: https://ay2324s1-cs2103-t16-2.github.io/tp/UserGuide.html#features
![image](https://github.com/AY2324S1-CS2103-T16-2/tp/assets/96569391/ac6e63fb-4312-4dec-9779-32581002f2d5)

In addition, as input is text-based, no forms of injection attacks will be rendered. No worries, thanks.
