### ISSUE TITLE
[PE-D][Tester A] Unsure the use of Remove Affiliation feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-T16-2/tp#186]
According to the User Guide, the command `removeah INDEX` will remove all affiliation history of the person that is at that index. However, I don't see where this come into use especially if the current affiliations are not removed, when will there be a case where there are non-current affiliations?

Because if for example, i have an affiliation between a doctor and a patient, the corresponding names' will be added in each profile. When I use `delete` on one of them, the affiliations is automatically removed as well.

![image.png](https://raw.githubusercontent.com/brendanneojw/ped/main/files/060b13d4-a4f0-4815-877b-7a3739712720.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: brendanneojw/ped#9

**Comment by leezhanpeng** [comment]
The removal of affiliations without deleting the person is possible using the `edit` function with `a/` without keywords.
