### ISSUE TITLE
[PE-D][Tester B] Adding names with s/o should be allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-T16-2/tp#195]
![Screenshot 2023-11-03 at 5.36.46 PM.png](https://raw.githubusercontent.com/elaineshijie/ped/main/files/1ca98605-1c0c-4ebc-82f3-575897a56005.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: elaineshijie/ped#8

**Comment by leezhanpeng** [comment]
Our application does not require a legal name. It is purely meant for the user to track Nurse, Doctors, and Patients under their own accord.
